package stream_api

const BUFFER_SIZE = 4500

const EVENT_BUFFER_SIZE = 256

var Stream_api = struct {
	DATA_STREAM_TIMESTAMP_OFFSET                 int
	DATA_STREAM_STREAM_MEMBER_ID                 int
	DATA_STREAM_STREAM_MEMBER_ID_LENGTH          int
	DATA_STREAM_STREAM_ROOM_ID                   int
	DATA_STREAM_STREAM_ROOM_ID_LENGTH            int
	DATA_STREAM_VIDEO_PAYLOAD_BYTE_LENGTH_OFFSET int
	DATA_STREAM_VIDEO_PAYLOAD_OFFSET             int
	DATA_STREAM_AUDIO_PAYLOAD_BYTE_LENGTH_OFFSET int
	DATA_STREAM_AUDIO_PAYLOAD_OFFSET             int
	DATA_STREAM_AUDIO_PAYLOAD_DURATION_OFFSET    int
	DATA_STREAM_CHAT_PAYLOAD_OFFSET              int
	DATA_STREAM_CHAT_PAYLOAD_BYTE_LENGTH_OFFSET  int

	DATA_STREAM_PLAYER_POSITION_OFFSET int
	DATA_STREAM_PLAYER_ROTATION_OFFSET int
}{0,
	4,
	16,
	20,
	16,
	36,
	128,
	40,
	-1,
	48,
	96,
	44,
	52,
	56,
}
